<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <Target Name="NpmBuild" BeforeTargets="Build">
    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)" />
    <Exec Command="npm run typecheck" WorkingDirectory="$(ProjectDir)" />
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <Target Name="NpmClean" BeforeTargets="Clean">
    <Exec Command="npm run clean" WorkingDirectory="$(ProjectDir)" />
  </Target>
</Project>
