trigger: none
schedules:
  - cron: "30 09 * * *"
    displayName: "Scheduled Trigger at 11:30"
    branches:
      include:
        - master
  - cron: "59 21 * * *"
    displayName: "Scheduled Trigger at 23:59"
    branches:
      include:
        - master

pool:
  vmImage: "windows-latest"

name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: "deployDataverse"
    displayName: "Deploy Dataverse"
    type: boolean
    values:
      - false
      - true
    default: true
  - name: "deployEconomyAreaFA"
    displayName: "Deploy EconomyArea Function App"
    type: boolean
    values:
      - false
      - true
    default: true
  - name: "deployInfrastructure"
    displayName: "Deploy Azure Infrastructure"
    type: boolean
    values:
      - false
      - true
    default: true

variables:
  - name: BuildConfiguration
    value: "release"
  - template: templates/dataverse/variables.yaml
  - name: DeployFunctions
    value: ${{ eq(parameters.deployEconomyAreaFA, true) }} # Wrap in an or-statement if you have multiple function apps to deploy

  ###########################################################################################
  #######################################    BUILD    #######################################
  ###########################################################################################
stages:
  - stage: Build_Application
    displayName: Build & Publish artifacts
    variables:
      - group: Dev
    jobs:
      - job: Build_And_Test
        displayName: Build and Test
        pool:
          vmImage: "windows-latest"
        steps:
          - template: templates/build-steps.yaml
          - ${{ if or(eq(variables.DeployFunctions, true), eq(parameters.deployInfrastructure, true)) }}:
              - template: templates/azure/publish-artifacts.yaml
          - ${{ if eq(parameters.deployDataverse, true) }}:
              - template: templates/dataverse/publish-artifacts.yaml

  ###########################################################################################
  ####################################### DEPLOY DEV  #######################################
  ###########################################################################################
  - stage: Deploy_Development
    displayName: Deploy to Dev
    dependsOn: Build_Application
    variables:
      - group: Dev
    jobs:
      - deployment: Deploy_Approval
        environment: Dev
        displayName: Deploy Approval
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Approved
      - template: templates/azure/deploy-infrastructure.yaml
        parameters:
          environment: Dev
          serviceConnectionName: "DEV"
          params: ${{parameters}}
      - template: templates/azure/deploy-function-apps.yaml
        parameters:
          environment: Dev
          serviceConnectionName: "DEV"
          params: ${{parameters}}

  ###########################################################################################
  ####################################### DEPLOY Rest #######################################
  ###########################################################################################
  - template: templates/deploy-environment.yaml
    parameters:
      environment: Test
      dataverseEnv: Test
      dependsOn: Deploy_Development
      params: ${{parameters}}

  - template: templates/deploy-environment.yaml
    parameters:
      environment: UAT
      dataverseEnv: UAT
      dependsOn: Deploy_Test
      params: ${{parameters}}

  - template: templates/deploy-environment.yaml
    parameters:
      environment: Prod
      dataverseEnv: Prod
      dependsOn: Deploy_UAT
      params: ${{parameters}}
